### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by darienmt** [vkhazin/play-framework-docker#1]
The "Detailed Instruction" link on README.md (https://www.linkedin.com/pulse/scala-play-restful-docker-container-vlad-khazin) is broken.

**Comment by vkhazin** [comment]
I have no idea why linkedin link is not working.
I have copied content of the article into readme.md file.

**Comment by vkhazin** [comment]
Awesome! I am not alone with the trouble:
http://community.linkedin.com/questions/340408/sorry-this-post-is-no-longer-available-1.html?
